### ISSUE TITLE
g_mime_part_get_openpgp_data returns GMIME_OPENPGP_DATA_NONE if part is base64 encoded

### ISSUE THREAD

**Issue by dkg** [jstedfast/gmime#60]
Some MTAs re-base64-encode everything, even if the content is in fact 7-bit clean.

The result is that some message parts get wrapped in base64 and have a `Content-Transfer-Encoding: base64` header added, even though they contain nothing but a `-----BEGIN PGP MESSAGE-----` block.  When calling `g_mime_part_get_openpgp_data()` on such a MIME part, it returns GMIME_OPENPGP_DATA_NONE, though i believe it should return GMIME_OPENPGP_DATA_ENCRYPTED.

**Comment by jstedfast** [comment]
What is the Content-Type of the MIME part containing this base64 encoded openpgp data?

Currently, the GMimeParser contains the logic for checking for openpgp boundaries which cannot peek into base64 encoded content.

That said, if the parser doesn't detect OpenPGP markers, it does this:

```c
if (encoding != GMIME_CONTENT_ENCODING_BASE64 && encoding != GMIME_CONTENT_ENCODING_UUENCODE) {
	/* If the Content-Transfer-Encoding is not obfuscated by base64 or uuencode,
	   then we can safely assume that no OpenPGP blocks exist. */
	g_mime_part_set_openpgp_data (mime_part, GMIME_OPENPGP_DATA_NONE);
} else if (!g_mime_content_type_is_type (content_type, "text", "*")) {
	/* The content is base64 or uuencoded, but it's not text so it should be safe
	   to assume that there won't be any OpenPGP blocks in the decoded content. */
	g_mime_part_set_openpgp_data (mime_part, GMIME_OPENPGP_DATA_NONE);
}
```

I'm *guessing* that the `else` branch is executing because the Content-Type is non-text?
